[path_input]
# path_df = "/home/dhaval.kadia/code/rst/cusum/main/20230803-091724__input_list_file_with_output_scores.csv"
# path_df_wavel7 = "/home/dhaval.kadia/code/rst/cusum/main/20231017-233737__input_list_file_with_output_scores.csv"
path_df = "20230803-091724__input_list_file_with_output_scores.csv"
path_df_wavel7 = "20231017-233737__input_list_file_with_output_scores.csv"


# primary colors
[color]
blue_005 = "#F3F9FC"
blue_020 = "#D0E4F0"
blue_040 = "#A3CAE1"
blue_060 = "#77B0D2"
blue_080 = "#4F96C4"
blue_100 = "#007CBA"