# paths to input files
[path_input]
path_df_metric = "config/spec-60-60.csv"

# paths to output files
[path_output]
path_figure = "figure/"

# primary colors
[color]
blue_005 = "#F3F9FC"
blue_020 = "#D0E4F0"
blue_040 = "#A3CAE1"
blue_060 = "#77B0D2"
blue_080 = "#4F96C4"
blue_100 = "#007CBA"

# controls
[control]
save_figure = "true"

# CUSUM parameters
[params_cusum]
list_ARL_0 = [50, 100, 150, 200, 300, 400, 500, 1000]
shift_in_mean = [
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9,
    1.0,
    1.1,
    1.2,
    1.3,
    1.4,
    1.5,
    1.6,
]
